// import HeaderNav from "@/components/HeaderNav";
// import "./globals.css";
// import { Inter } from "next/font/google";

// import Footer from "@/components/Footer";
// import { Lato } from "next/font/google";
// const lato = Lato({
//   variable: "--font-lato",
//   weight: ["300", "400", "700", "100", "900"],
//   subsets: ["latin"],
// });
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={lato.className}>
//         <HeaderNav />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
