export const linkData = [
  {
    name: "Home",
    path: "/",
  },
  {
    name: "About",
    path: "/about",
  },
  {
    name: "Calendar",
    path: "/calendar",
  },
  {
    name: "Photos",
    path: "/photos",
  },
  {
    name: "Audio",
    path: "/audio",
  },
  {
    name: "Contact",
    path: "/contact",
  },
];

export const tourInfo = [
  {
    name: "RADIANCE",
    instruments: "FLUTE, TRUMPET, PIANO",
    description:
      "Concert featuring exciting contemporary works by Stephenson, Elkins, and Debussy.",
    image: "/images/tour-images/piano-md.webp",
    dates: [
      {
        id: 1,
        month: "SEPTEMBER",
        date: "6",
        year: "2024",
        city: "Fort Myers, FL",
        time: "1:00 PM",
      },
      {
        id: 2,
        month: "SEPTEMBER",
        date: "7",
        year: "2024",
        city: "Fort Myers, FL",
        time: "7:30 PM",
      },
      // {
      //   id: 3,
      //   month: "SEPTEMBER",
      //   date: "",
      //   year: "2023",
      //   city: "Charleston, SC",
      //   time: "3:00 PM",
      // },
      // {
      //   id: 4,
      //   month: "AUGUST",
      //   date: "14",
      //   year: "2023",
      //   city: "Augusta, GA",
      //   time: "7:30 PM",
      // },
      // {
      //   id: 5,
      //   month: "AUGUST",
      //   date: "16",
      //   year: "2023",
      //   city: "Highlands, NC",
      //   time: "2:00 PM",
      // },
    ],
  },
  {
    name: "BAROQUE DISCOVERIES",
    instruments: "FLUTE, VIOLIN, CELLO, HARPSICHORD",
    description:
      "Program will introduce the audience to lesser known works by familiar composers, including J.S. Bach, Telemann, Vivaldi, C.P.E. Bach, and Handel.",
    image: "/images/tour-images/Harpsichord.jpg",
    dates: [
      {
        id: 1,
        month: "SEPTEMBER",
        date: "14",
        year: "2024",
        city: "Washington CH, OH",
        time: "7:00 PM",
      },
      {
        id: 2,
        month: "SEPTEMBER",
        date: "15",
        year: "2024",
        city: "Canton, OH",
        time: "3:00 PM",
      },
      {
        id: 3,
        month: "SEPTEMBER",
        date: "16",
        year: "2024",
        city: "Kensington, PA",
        time: "6:30 PM",
      },
      {
        id: 4,
        month: "SEPTEMBER",
        date: "18",
        year: "2024",
        city: "Hiram, OH",
        time: "7:00 PM",
      },
      {
        id: 5,
        month: "SEPTEMBER",
        date: "19",
        year: "2024",
        city: "Carey, OH",
        time: "7:00 PM",
      },
      {
        id: 6,
        month: "SEPTEMBER",
        date: "20",
        year: "2024",
        city: "Toledo, OH",
        time: "7:00 PM",
      },
      {
        id: 7,
        month: "SEPTEMBER",
        date: "21",
        year: "2024",
        city: "Mansfield, OH",
        time: "7:00 PM",
      },
      {
        id: 8,
        month: "SEPTEMBER",
        date: "22",
        year: "2024",
        city: "Westerville, OH",
        time: "2:00 PM",
      },
    ],
  },
  {
    name: "REVERIE",
    instruments: "FLUTE, VIOLA, HARP",
    description:
      "Concert featuring Debussy's inspirational trio, a lovely sonatine by Ravel, and other works by Rota, Reger, and Scarlatti.",
    image: "/images/tour-images/harp.webp",
    dates: [
      {
        id: 0,
        month: "OCTOBER",
        date: "18",
        year: "2024",
        city: "Tryon, NC",
        time: "7:00 PM",
      },
      {
        id: 1,
        month: "OCTOBER",
        date: "19",
        year: "2024",
        city: "Winston-Salem, NC",
        time: "4:00 PM",
      },
      {
        id: 2,
        month: "OCTOBER",
        date: "21",
        year: "2024",
        city: "Huntersville, NC",
        time: "7:00 PM",
      },
      {
        id: 3,
        month: "OCTOBER",
        date: "22",
        year: "2024",
        city: "Augusta, GA",
        time: "7:00 PM",
      },
      {
        id: 4,
        month: "OCTOBER",
        date: "24",
        year: "2024",
        city: "Columbia, SC",
        time: "7:00 PM",
      },
      {
        id: 5,
        month: "OCTOBER",
        date: "25",
        year: "2024",
        city: "Murrells Inlet, SC",
        time: "6:00 PM",
      },
      {
        id: 6,
        month: "OCTOBER",
        date: "27",
        year: "2024",
        city: "Oriental, NC",
        time: "4:30 PM",
      },
    ],
  },
  {
    name: "HOLIDAY BAROQUE",
    instruments: "FLUTE, VIOLIN, CELLO, HARPSICHORD",
    description:
      "Holiday favorites and baroque repertoire to fit the spirit of the season.",
    image: "/images/tour-images/firTree.webp",
    dates: [
      {
        id: 1,
        month: "DECEMBER",
        date: "6",
        year: "2024",
        city: "Summerville, SC",
        time: "7:00 PM",
      },
      {
        id: 2,
        month: "DECEMBER",
        date: "7",
        year: "2024",
        city: "Charleston, SC",
        time: "7:00 PM",
      },
      {
        id: 3,
        month: "DECEMBER",
        date: "8",
        year: "2024",
        city: "Savannah, GA",
        time: "4:00 PM",
      },
      {
        id: 4,
        month: "DECEMBER",
        date: "9",
        year: "2024",
        city: "New Smyrna Beach, FL",
        time: "6:00 PM",
      },
      {
        id: 5,
        month: "DECEMBER",
        date: "10",
        year: "2024",
        city: "DeLand, FL",
        time: "7:00 PM",
      },
      {
        id: 6,
        month: "DECEMBER",
        date: "11",
        year: "2024",
        city: "Sebring, FL",
        time: "7:00 PM",
      },
      {
        id: 7,
        month: "DECEMBER",
        date: "13",
        year: "2024",
        city: "Stuart, FL",
        time: "7:00 PM",
      },
      {
        id: 8,
        month: "DECEMBER",
        date: "15",
        year: "2024",
        city: "Sanibel Island, FL",
        time: "2:00 PM",
      },
      // {
      //   id: 8,
      //   month: "DECEMBER",
      //   date: "10",
      //   year: "2023",
      //   city: "Clearwater, FL",
      //   time: "3:00 PM",
      // },
    ],
  },
  {
    name: "NEW HORIZONS",
    instruments: "FLUTE, VIOLIN, PIANO",
    description:
      "Introducing the audience to something new with works by Rota, Andriessen, Mel Bonis, and Karg-Elert",
    image: "/images/tour-images/flute-md.webp",
    dates: [
      // {
      //   id: 0,
      //   month: "JANUARY",
      //   date: "19",
      //   year: "2025",
      //   city: "Vero Beach, FL",
      //   time: "TBD",
      // },
      {
        id: 1,
        month: "JANUARY",
        date: "21",
        year: "2025",
        city: "Live Oak, FL",
        time: "7:30 PM",
      },
      {
        id: 2,
        month: "JANUARY",
        date: "22",
        year: "2025",
        city: "Leesburg, FL",
        time: "6:30 PM",
      },
      {
        id: 3,
        month: "JANUARY",
        date: "24",
        year: "2025",
        city: "Fort Myers, FL",
        time: "7:00 PM",
      },
      {
        id: 4,
        month: "JANUARY",
        date: "25",
        year: "2025",
        city: "Tampa, FL",
        time: "7:00 PM",
      },
      {
        id: 5,
        month: "JANUARY",
        date: "26",
        year: "2025",
        city: "Ormond Beach, FL",
        time: "3:00 PM",
      },
    ],
  },
  // {
  //   name: "ROMANZA",
  //   instruments: "FLUTE, TRUMPET, PIANO",
  //   description:
  //     "Valentine’s program sharing love stories and expressive works.",
  //   image: "/images/tour-images/piano-md.webp",
  //   dates: [
  //     {
  //       id: 0,
  //       month: "FEBRUARY",
  //       date: "8",
  //       year: "2025",
  //       city: "St. Augustine, FL",
  //       time: "7:00 PM",
  //     },
  //     {
  //       id: 1,
  //       month: "FEBRUARY",
  //       date: "10",
  //       year: "2025",
  //       city: "Daytona Beach, FL",
  //       time: "11:15 AM",
  //     },
  //     {
  //       id: 2,
  //       month: "FEBRUARY",
  //       date: "12",
  //       year: "2025",
  //       city: "Lake City, FL",
  //       time: "6:30 PM",
  //     },
  //     {
  //       id: 3,
  //       month: "FEBRUARY",
  //       date: "14",
  //       year: "2025",
  //       city: "Fort Myers, FL",
  //       time: "7:30 PM",
  //     },
  //     {
  //       id: 4,
  //       month: "FEBRUARY",
  //       date: "15",
  //       year: "2025",
  //       city: "Coral Springs, FL",
  //       time: "7:00 PM",
  //     },
  //     {
  //       id: 5,
  //       month: "FEBRUARY",
  //       date: "16",
  //       year: "2025",
  //       city: "Longboat Key, FL",
  //       time: "2:00 PM",
  //     },
  //     // {
  //     //   id: 4,
  //     //   month: "FEBRUARY",
  //     //   date: "12",
  //     //   year: "2024",
  //     //   city: "Sarasota, FL",
  //     //   time: "7:30 PM",
  //     // },

  //     // {
  //     //   id: 6,
  //     //   month: "FEBRUARY",
  //     //   date: "15",
  //     //   year: "2024",
  //     //   city: "DeLand, FL",
  //     //   time: "7:30 PM",
  //     // },
  //     // {
  //     //   id: 7,
  //     //   month: "FEBRUARY",
  //     //   date: "18",
  //     //   year: "2024",
  //     //   city: "Sun City Center, FL",
  //     //   time: "3:00 PM",
  //     // },
  //   ],
  // },
  // {
  //   name: "ROMANZA",
  //   instruments: "FLUTE, TRUMPET, PIANO",
  //   description:
  //     "Valentine’s program sharing love stories and expressive works.",
  //   image: "/images/tour-images/piano-md.webp",
  //   dates: [
  //     {
  //       id: 0,
  //       month: "FEBRUARY",
  //       date: "8",
  //       year: "2025",
  //       city: "St. Augustine, FL",
  //       time: "7:00 PM",
  //     },
  //     {
  //       id: 1,
  //       month: "FEBRUARY",
  //       date: "10",
  //       year: "2025",
  //       city: "Daytona Beach, FL",
  //       time: "11:15 AM",
  //     },
  //     {
  //       id: 2,
  //       month: "FEBRUARY",
  //       date: "12",
  //       year: "2025",
  //       city: "Lake City, FL",
  //       time: "6:30 PM",
  //     },
  //     {
  //       id: 3,
  //       month: "FEBRUARY",
  //       date: "14",
  //       year: "2025",
  //       city: "Fort Myers, FL",
  //       time: "7:30 PM",
  //     },
  //     {
  //       id: 4,
  //       month: "FEBRUARY",
  //       date: "15",
  //       year: "2025",
  //       city: "Coral Springs, FL",
  //       time: "7:00 PM",
  //     },
  //     {
  //       id: 5,
  //       month: "FEBRUARY",
  //       date: "16",
  //       year: "2025",
  //       city: "Longboat Key, FL",
  //       time: "2:00 PM",
  //     },
  //     // {
  //     //   id: 4,
  //     //   month: "FEBRUARY",
  //     //   date: "12",
  //     //   year: "2024",
  //     //   city: "Sarasota, FL",
  //     //   time: "7:30 PM",
  //     // },

  //     // {
  //     //   id: 6,
  //     //   month: "FEBRUARY",
  //     //   date: "15",
  //     //   year: "2024",
  //     //   city: "DeLand, FL",
  //     //   time: "7:30 PM",
  //     // },
  //     // {
  //     //   id: 7,
  //     //   month: "FEBRUARY",
  //     //   date: "18",
  //     //   year: "2024",
  //     //   city: "Sun City Center, FL",
  //     //   time: "3:00 PM",
  //     // },
  //   ],
  // },
  {
    name: "FANTAISIE D'AMOUR",
    instruments: "FLUTE, TRUMPET, PIANO",
    description:
      "Valentine’s program with works by Rubtsov, Stephenson, Schumann, Gaubert, and Widor.",
    image: "/images/tour-images/piano-md.webp",
    dates: [
      {
        id: 0,
        month: "FEBRUARY",
        date: "8",
        year: "2025",
        city: "St. Augustine, FL",
        time: "7:00 PM",
      },
      {
        id: 1,
        month: "FEBRUARY",
        date: "10",
        year: "2025",
        city: "Daytona Beach, FL",
        time: "11:15 AM",
      },
      {
        id: 2,
        month: "FEBRUARY",
        date: "12",
        year: "2025",
        city: "Lake City, FL",
        time: "6:30 PM",
      },
      {
        id: 3,
        month: "FEBRUARY",
        date: "14",
        year: "2025",
        city: "Fort Myers, FL",
        time: "7:30 PM",
      },
      {
        id: 4,
        month: "FEBRUARY",
        date: "15",
        year: "2025",
        city: "Coral Springs, FL",
        time: "7:00 PM",
      },
      {
        id: 5,
        month: "FEBRUARY",
        date: "16",
        year: "2025",
        city: "Longboat Key, FL",
        time: "2:00 PM",
      },
      // {
      //   id: 4,
      //   month: "FEBRUARY",
      //   date: "12",
      //   year: "2024",
      //   city: "Sarasota, FL",
      //   time: "7:30 PM",
      // },

      // {
      //   id: 6,
      //   month: "FEBRUARY",
      //   date: "15",
      //   year: "2024",
      //   city: "DeLand, FL",
      //   time: "7:30 PM",
      // },
      // {
      //   id: 7,
      //   month: "FEBRUARY",
      //   date: "18",
      //   year: "2024",
      //   city: "Sun City Center, FL",
      //   time: "3:00 PM",
      // },
    ],
  },
  {
    name: "VOYAGE",
    instruments: "FLUTE, HARP",
    description:
      "Exploring music from different countries with works by Rota, Mozart, and Cras",
    image: "/images/tour-images/flute-md.webp",
    dates: [
      {
        id: 0,
        month: "MARCH",
        date: "12",
        year: "2025",
        city: "Venice, FL",
        time: "2:00 PM",
      },
      {
        id: 1,
        month: "MARCH",
        date: "12",
        year: "2025",
        city: "Sarasota, FL",
        time: "6:30 PM",
      },
      // {
      //   id: 2,
      //   month: "FEBRUARY",
      //   date: "12",
      //   year: "2025",
      //   city: "Lake City, FL",
      //   time: "6:30 PM",
      // },
      // {
      //   id: 3,
      //   month: "FEBRUARY",
      //   date: "14",
      //   year: "2025",
      //   city: "Fort Myers, FL",
      //   time: "7:30 PM",
      // },
      // {
      //   id: 4,
      //   month: "FEBRUARY",
      //   date: "15",
      //   year: "2025",
      //   city: "Coral Springs, FL",
      //   time: "7:00 PM",
      // },
      // {
      //   id: 5,
      //   month: "FEBRUARY",
      //   date: "16",
      //   year: "2025",
      //   city: "Longboat Key, FL",
      //   time: "2:00 PM",
      // },
      // {
      //   id: 4,
      //   month: "FEBRUARY",
      //   date: "12",
      //   year: "2024",
      //   city: "Sarasota, FL",
      //   time: "7:30 PM",
      // },

      // {
      //   id: 6,
      //   month: "FEBRUARY",
      //   date: "15",
      //   year: "2024",
      //   city: "DeLand, FL",
      //   time: "7:30 PM",
      // },
      // {
      //   id: 7,
      //   month: "FEBRUARY",
      //   date: "18",
      //   year: "2024",
      //   city: "Sun City Center, FL",
      //   time: "3:00 PM",
      // },
    ],
  },
  {
    name: "REVERIE",
    instruments: "FLUTE, VIOLA, HARP",
    description:
      "Concert featuring Debussy's monumental trio and other works by Ibert, Cras, and J.S. Bach.",
    image: "/images/tour-images/harp.webp",
    dates: [
      {
        id: 0,
        month: "MARCH",
        date: "23",
        year: "2025",
        city: "Brecksville, OH",
        time: "4:00 PM",
      },
      {
        id: 1,
        month: "MARCH",
        date: "25",
        year: "2025",
        city: "Avon Lake, OH",
        time: "7:30 PM",
      },
      {
        id: 2,
        month: "MARCH",
        date: "26",
        year: "2025",
        city: "Milan, OH",
        time: "7:00 PM",
      },
      {
        id: 3,
        month: "MARCH",
        date: "27",
        year: "2025",
        city: "Pittsburgh, PA",
        time: "7:00 PM",
      },
      {
        id: 4,
        month: "MARCH",
        date: "28",
        year: "2025",
        city: "Canton, OH",
        time: "7:00 PM",
      },
      {
        id: 5,
        month: "MARCH",
        date: "29",
        year: "2025",
        city: "Greenville, PA",
        time: "7:00 PM",
      },
      {
        id: 6,
        month: "MARCH",
        date: "30",
        year: "2025",
        city: "Warren, PA",
        time: "4:00 PM",
      },
      {
        id: 7,
        month: "MARCH",
        date: "31",
        year: "2025",
        city: "Warren, PA",
        time: "9:00 AM and 1:00 PM",
      },
      // {
      //   id: 6,
      //   month: "MARCH",
      //   date: "9",
      //   year: "2024",
      //   city: "Savannah, GA",
      //   time: "11:00 AM",
      // },
      // {
      //   id: 7,
      //   month: "MARCH",
      //   date: "10",
      //   year: "2024",
      //   city: "St. Simons Island, GA",
      //   time: "5:00 PM",
      // },
    ],
  },
  {
    name: "WOMEN IN MUSIC",
    instruments: "FLUTE, CELLO, PIANO",
    description:
      "Program featuring female composers for Mother's Day. Music by Amanda Harberg, Mel Bonis, Dani Howard, Annabelle Chvostek, and Fannie Mendelssohn.",
    image: "/images/tour-images/cello-md.webp",
    dates: [
      {
        id: 1,
        month: "MAY",
        date: "4",
        year: "2025",
        city: "Penny Farms, FL",
        time: "7:00 PM",
      },
      {
        id: 2,
        month: "MAY",
        date: "5",
        year: "2025",
        city: "Atlantic Beach, FL",
        time: "2:00 PM",
      },
      {
        id: 20,
        month: "MAY",
        date: "7",
        year: "2025",
        city: "Pawleys Island, SC",
        time: "6:00 PM",
      },
      {
        id: 21,
        month: "MAY",
        date: "8",
        year: "2025",
        city: "House Concert",
        time: "3:00 PM",
      },
      {
        id: 3,
        month: "MAY",
        date: "9",
        year: "2025",
        city: "Charleston, SC",
        time: "7:00 PM",
      },
      {
        id: 4,
        month: "MAY",
        date: "11",
        year: "2025",
        city: "Pinehurst, NC",
        time: "2:00 PM",
      },
      // {
      //   id: 5,
      //   month: "MAY",
      //   date: "21",
      //   year: "2024",
      //   city: "Ashland, OH",
      //   time: "3:00 PM",
      // },
    ],
  },
  {
    name: "VOYAGE",
    instruments: "FLUTE and PIANO",
    description: "",
    image: "/images/tour-images/flute-md.webp",
    dates: [
      {
        id: 0,
        month: "JULY",
        date: "17",
        year: "2025",
        city: "Sarasota, FL",
        time: "7:30 PM",
      },
      {
        id: 1,
        month: "JULY",
        date: "18",
        year: "2025",
        city: "Venice, FL",
        time: "3:00 PM",
      },
      {
        id: 2,
        month: "JULY",
        date: "21",
        year: "2025",
        city: "Sarasota, FL",
        time: "8:00 PM",
      },
      {
        id: 3,
        month: "JULY",
        date: "23",
        year: "2025",
        city: "Boca Raton, FL",
        time: "7:30 PM",
      },
      // {
      //   id: 2,
      //   month: "JUNE",
      //   date: "9",
      //   year: "2024",
      //   city: "Gainesville, GA",
      //   time: "2:00 PM",
      // },
      // {
      //   id: 3,
      //   month: "JUNE",
      //   date: "10",
      //   year: "2024",
      //   city: "Sunset, SC",
      //   time: "7:30 PM",
      // },
    ],
  },
  // {
  //   name: "PATHWAYS",
  //   instruments: "FLUTE and PIANO",
  //   description: "",
  //   image: "/images/tour-images/flute-md.webp",
  //   dates: [
  //     {
  //       id: 1,
  //       month: "JULY",
  //       date: "15",
  //       year: "2024",
  //       city: "Sarasota, FL",
  //       time: "8:00 PM",
  //     },
  //     {
  //       id: 2,
  //       month: "JULY",
  //       date: "16",
  //       year: "2024",
  //       city: "Fort Myers, FL",
  //       time: "1:00 PM",
  //     },
  //     {
  //       id: 3,
  //       month: "JULY",
  //       date: "17",
  //       year: "2024",
  //       city: "Venice, FL",
  //       time: "4:00 PM",
  //     },
  //     {
  //       id: 4,
  //       month: "JULY",
  //       date: "18",
  //       year: "2024",
  //       city: "Fort Myers, FL",
  //       time: "7:00 PM",
  //     },
  //     {
  //       id: 5,
  //       month: "JULY",
  //       date: "19",
  //       year: "2024",
  //       city: "Boca Raton, FL",
  //       time: "7:30 PM",
  //     },
  //     {
  //       id: 6,
  //       month: "JULY",
  //       date: "20",
  //       year: "2024",
  //       city: "Pompano Beach, FL",
  //       time: "2:00 PM",
  //     },
  //   ],
  // },
];

export const videos = [
  {
    name: "Debussy - Sonata for Flute, Viola, and Harp",
    src: "https://www.youtube.com/embed/zIGkBaecnLk",
  },
  {
    name: "Telemann - Trio Sonata in D Minor",
    src: "https://www.youtube.com/embed/RXQS01D5Qpo",
  },
  {
    name: "Vivaldi - Chamber Concerto in D Major",
    src: "https://www.youtube.com/embed/wTgnQCcYqBw",
  },
  {
    name: "Andriessen - Intermezzo",
    src: "https://www.youtube.com/embed/U-E4MuFzM-s",
  },
  {
    name: "Liebermann - Soliloquy",
    src: "https://www.youtube.com/embed/zjwc6aRV0E8",
  },
  {
    name: "Dorff - Ballade",
    src: "https://www.youtube.com/embed/mKXSUwx4t9s",
  },
  {
    name: "Ibert - Deux Interludes: Mvt. 1",
    src: "https://www.youtube.com/embed/8iaRWpIWD-Q",
  },
  {
    name: "Saint-Saens - Odelette",
    src: "https://www.youtube.com/embed/Xmu9AQtysv4",
  },
  {
    name: "Dorff - Atomic Turquoise",
    src: "https://www.youtube.com/embed/AeviP7fQSIw",
  },
  {
    name: "Kurt Bestor - First Noel",
    src: "https://www.youtube.com/embed/rFgHZLOk24M",
  },
  {
    name: "Vaughn-Williams - Greensleeves",
    src: "https://www.youtube.com/embed/bCJHttMaOzk",
  },

  // {
  //   name: "Farrenc - Trio: Mvt. 1",
  //   src: "https://www.youtube.com/embed/yLgEylUgaFI",
  // },

  {
    name: "Harty - In Ireland",
    src: "https://www.youtube.com/embed/d9ZN20MBTrg",
  },
  {
    name: "Beethoven - Romance in F",
    src: "https://www.youtube.com/embed/mVlliRERmzw",
  },

  // {
  //   name: "Kersten - Song of the Woods",
  //   src: "https://www.youtube.com/embed/XwBOhjWNSHM",
  // },

  // {
  //   name: "Farrenc - Trio: Mvt. 2",
  //   src: "https://www.youtube.com/embed/8eOWtNqH0nM",
  // },
  {
    name: "Mauldin - Mountain Winds: Mvt. 4",
    src: "https://www.youtube.com/embed/6IKIQcAoz40",
  },
];

export const images = [
  {
    src: "/images/carousel/cover5.JPG",
    alt: "Baroque Quartet",
  },
  {
    src: "/images/carousel/cover2.webp",
    alt: "Concert Photo",
  },
  {
    src: "/images/carousel/cover3.webp",
    alt: "Duo Photo",
  },
  {
    src: "/images/carousel/Performance.webp",
    alt: "Perfomance Photo",
  },
];

export const publicity = [
  {
    src: "/images/carousel/cover5.JPG",
    alt: "Baroque Quartet 1",
  },
  {
    src: "/images/carousel/AngNLaura.jpg",
    alt: "Angela and Laura",
  },
  // {
  //   src: "/images/publicity/BaroquePhoto3.jpg",
  //   alt: "Baroque Quartet 3",
  // },
  // {
  //   src: "/images/publicity/BaroquePhoto4.jpg",
  //   alt: "Baroque Quartet 4",
  // },
  // {
  //   src: "/images/publicity/pianotrio1.jpg",
  //   alt: "Flute Trumpet Trio 1",
  // },
  // {
  //   src: "/images/publicity/pianotrio2.jpeg",
  //   alt: "Flute Trumpet Trio 2",
  // },
  {
    src: "/images/publicity/triophotocrop.JPG",
    alt: "Flute Trumpet Trio 1",
  },
  {
    src: "/images/publicity/KrisAngela2edit.jpg",
    alt: "Flute Trumpet",
  },
  // {
  //   src: "/images/publicity/DuoPhoto4.jpg",
  //   alt: "Flute Piano Duo",
  // },
  {
    src: "/images/publicity/DuoPhoto1crop.jpg",
    alt: "Flute Piano Duo",
  },
  {
    src: "/images/publicity/DuoPhoto3.JPG",
    alt: "Flute Piano Duo",
  },
  // {
  //   src: "/images/publicity/DuoPhoto3.jpg",
  //   alt: "Flute Piano Duo",
  // },
  {
    src: "/images/publicity/PhotoTrio1.jpg",
    alt: "Flute Harp Trumpet",
  },
  {
    src: "/images/publicity/PhotoDuo4.jpg",
    alt: "Flute Harp 1",
  },
  {
    src: "/images/publicity/PhotoDuo5.jpg",
    alt: "Flute Harp 2",
  },
  {
    src: "/images/publicity/PhotoDuo6.jpg",
    alt: "Flute Harp 3",
  },
];

export const headshots = [
  {
    src: "/images/members/angela3.webp",
    alt: "Angela Smiling in front of Greenery",
  },
  {
    src: "/images/members/2.webp",
    alt: "Angela in field looking off into distance",
  },
  {
    src: "/images/members/3.webp",
    alt: "Angela Serious in front of Greenery",
  },
  {
    src: "/images/members/4.webp",
    alt: "Kris sitting on a bench with Trumpet",
  },
  {
    src: "/images/members/5.webp",
    alt: "Kris Smiling in front of trees",
  },
  {
    src: "/images/members/7.webp",
    alt: "Paul Smiling in front of Greenery with Violin in hand",
  },
  {
    src: "/images/members/Paul.webp",
    alt: "Paul in front of Harpsichord",
  },
  {
    src: "/images/members/RachelA.webp",
    alt: "Rachel Aguilar smiling with Violin in hand",
  },
  // {
  //   src: "/images/members/9.webp",
  //   alt: "Paulo with violin looking into distance",
  // },
  {
    src: "/images/members/10.webp",
    alt: "Laura with Cello",
  },
  {
    src: "/images/members/11.webp",
    alt: "Laura with Cello sideways",
  },
  // {
  //   src: "/images/members/12.webp",
  //   alt: "Rachel O'Brien outside with Harp",
  // },
  // {
  //   src: "/images/members/13.webp",
  //   alt: "Rachel at Harp with serious look",
  // },
  // {
  //   src: "/images/members/14.webp",
  //   alt: "Rachel standing next to Harp",
  // },
  {
    src: "/images/members/Alexandra.jpg",
    alt: "Alexandra sitting at Harpsichord",
  },
  {
    src: "/images/members/16.webp",
    alt: "Caroline at Piano with serious look",
  },
  {
    src: "/images/members/17b.webp",
    alt: "Caroline Outside smiling",
  },
  {
    src: "/images/members/18.webp",
    alt: "Caroline sitting at piano smiling",
  },
  // {
  //   src: "/images/members/ZhangPhoto.webp",
  //   alt: "Keru standing next to piano smiling",
  // },
];

export const pastPerformances = [
  {
    src: "/images/past/21.JPG",
    alt: "Baroque Quartet 4",
  },
  {
    src: "/images/past/22.JPG",
    alt: "Baroque Quartet 5",
  },
  // {
  //   src: "/images/past/1.jpg",
  //   alt: "Baroque Quartet 1",
  // },
  // {
  //   src: "/images/past/2.jpg",
  //   alt: "Baroque Quartet 2",
  // },
  // {
  //   src: "/images/past/3.JPG",
  //   alt: "Baroque Quartet 3",
  // },
  {
    src: "/images/past/4.jpg",
    alt: "Flute Harp Duo 1",
  },
  {
    src: "/images/past/5.JPEG",
    alt: "Flute Harp Duo 2",
  },
  {
    src: "/images/publicity/PhotoDuo3.jpg",
    alt: "Flute Harp 2",
  },
  {
    src: "/images/past/7.jpg",
    alt: "Flute Piano Duo 1",
  },
  {
    src: "/images/past/8.jpg",
    alt: "Flute Piano Duo 2",
  },
  {
    src: "/images/past/9.jpg",
    alt: "Flute Piano Duo 3",
  },
  {
    src: "/images/past/10.jpg",
    alt: "Flute Piano Duo 4",
  },
  {
    src: "/images/past/11.JPG",
    alt: "Flute Piano Duo 5",
  },
  {
    src: "/images/past/12.jpg",
    alt: "Flute Trumpet Harp 1",
  },
  {
    src: "/images/past/13.jpg",
    alt: "Flute Trumpet Harp 2",
  },
  {
    src: "/images/past/14.JPG",
    alt: "Flute and Harp Performance",
  },
  {
    src: "/images/past/15.JPG",
    alt: "Flute Harp",
  },
  {
    src: "/images/past/16.JPG",
    alt: "Flute Harp",
  },
  {
    src: "/images/past/17.JPG",
    alt: "Flute Harp Phoebe",
  },
  {
    src: "/images/past/18.JPG",
    alt: "Flute Trumpet",
  },
  {
    src: "/images/past/19.JPG",
    alt: "Flute Cello Piano 1",
  },
  {
    src: "/images/past/20.jpg",
    alt: "Flute Cello Piano 2",
  },
];
